2.10BSD (1987)
Released by Keith Bostic and Casey Leedom; distributed by USENIX
starting in fall 1987. Brings much of 4.3BSD to the PDP-11.

Source: https://www.tuhs.org/Archive/Distributions/UCB/2BSD/2.10bsd.tar.gz
(the unpacked "root" tree)

Import notes: kept 8049 files; dropped 523 a.out executables (PDP-11/VAX); dropped 131 other binary files (data, boot blocks, generated string tables); dropped 32 compiled object libraries.

Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01Vb1qstb69mh3NKDCWZ2NBD

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,26 +1,38 @@
-:  rc for use with autoreboot
-:  '/etc/rc [ autoboot | fastboot  [ powerfail | "" ] ]'
 HOME=/; export HOME
-PATH=/etc:/bin:/usr/bin; export PATH
-case $2 in 
-powerfail)
+PATH=/bin:/usr/bin
+
+# If you have a ram disk configured into your system which is listed in
+# /etc/fstab, you'll have to do a mkfs on it here.
+RAMSIZE=150
+/etc/mkfs /dev/ram ${RAMSIZE} 1 2
+
+if [ $2x = powerfailx ]
+then
 	echo REBOOTING AFTER POWER FAILURE >/dev/console
-	;;
-esac
-case $1 in
-autoboot)
+fi
+if [ $1x = fastbootx ]
+then
+	echo Fast boot ... skipping disk checks >/dev/console
+elif [ $1x = autobootx ]
+then
 	echo Automatic reboot in progress... >/dev/console
 	date >/dev/console
-	fsck -p -t fsck.tmp >/dev/console 2>&1
+# This will *only* work if fsck can do your root file system without a
+# temporary file, and if the root file system is checked alone on a pass
+# by itself -- be careful!  This can *seriously* mess you up.
+	/etc/fsck -p -t /_FSCK_TMP_FILE >/dev/console
 	case $? in
 	0)
+		date >/dev/console
+		;;
+	2)
+		exit 1
 		;;
 	4)
-		echo "Root was modified-- rebooting." >/dev/console
-		reboot -n
+		/etc/reboot -n
 		;;
 	8)
-		echo "Automatic filesystem check failed... help!" >/dev/console
+		echo "Automatic reboot failed... help!" >/dev/console
 		exit 1
 		;;
 	12)
@@ -32,22 +44,61 @@ autoboot)
 		exit 1
 		;;
 	esac
-;;
-esac
-date >/dev/console
+else
+	date >/dev/console
+fi
+
+# attempt to rationally recover the passwd file if needed
+if [ -s /etc/ptmp ]
+then
+	if [ -s /etc/passwd ]
+	then
+		ls -l /etc/passwd /etc/ptmp >/dev/console
+		rm -f /etc/ptmp		# should really remove the shorter
+	else
+		echo 'passwd file recovered from ptmp' >/dev/console
+		mv /etc/ptmp /etc/passwd
+	fi
+elif [ -r /etc/ptmp ]
+then
+	echo 'removing passwd lock file' >/dev/console
+	rm -f /etc/ptmp
+fi
+
+/etc/umount -a
 cp /dev/null /etc/mtab
-cp /dev/null /etc/utmp
-mount -a			>/dev/console 2>&1
-savecore /usr/sys >/dev/console 2>&1
-/usr/lib/ex3.7preserve -a
-rm -rf /usr/tmp/*
-rm -rf /tmp/*
-rm -f /usr/spool/uucp/LCK..*
-rm -f /usr/spool/lpd/lock
-rm -f /usr/spool/vpd/lock
-/etc/update
-/etc/cron
-ps -U
-/etc/accton /usr/adm/acct
-/etc/hostname hostnameunknown
+/etc/mount -a						>/dev/console 2>&1
+
+/bin/ps -U						>/dev/console 2>&1
+rm -f /etc/nologin
+rm -f /usr/spool/uucp/LCK.*
+chmod 666 /dev/tty[pqrs]*
+
+sh /etc/rc.local
+
+#				echo preserving editor files 	>/dev/console
+#(cd /tmp; /usr/lib/ex3.7preserve -a)
+#				echo clearing /tmp 		>/dev/console
+#(cd /tmp; find . ! -name . ! -name lost+found -exec rm -r {} \; )
+
+				echo -n standard daemons:	>/dev/console
+/etc/update;			echo -n ' update'		>/dev/console
+/etc/cron;			echo -n ' cron'			>/dev/console
+/etc/accton /usr/adm/acct;	echo -n ' accounting'		>/dev/console
+				echo '.'			>/dev/console
+
+echo -n starting network daemons:				>/dev/console
+if [ -f /etc/rwhod ]; then
+	/etc/rwhod;		echo -n ' rwhod'		>/dev/console
+fi
+if [ -f /etc/inetd ]; then
+	/etc/inetd;		echo -n ' inetd'		>/dev/console
+fi
+#if [ -f /usr/lib/lpd ]; then
+#	rm -f /dev/printer
+#	/usr/lib/lpd;		echo -n ' printer'		>/dev/console
+#fi
+				echo '.'			>/dev/console
+
+				date				>/dev/console
 exit 0
diff --git a/usr/src/sys/conf/config b/usr/src/sys/conf/config
--- a/usr/src/sys/conf/config
+++ b/usr/src/sys/conf/config
@@ -1,356 +1,259 @@
 #! /bin/sh
-#	script to set up a new kernel configuration directory.
-#	Usage:	MAKE machineid
-#	to make a directory for "machineid"
+#
+#	2.10BSD script to set up a new kernel configuration directory.
 
-case $# in
-	1) ;;
-	*) echo "Usage: MAKE machinename"
-		echo " to make a configuration directory ../machinename"
-		echo " from the description file ./machinename"
-		echo " and copy the necessary files into it."
-		exit 1
-		;;
-esac
+LO=../h/localopts.h
 
-:  set defaults
-pdp11="GENERIC"
-ident="UNKNOWN"
-maxusers=4
-bootdev="none"
-timezone=8
-dst=1
-rootdev="UNSPECIFIED"
-swapdev="UNSPECIFIED"
-dumpdev="UNSPECIFIED"
-pipedev="UNSPECIFIED"
-swplo="UNSPECIFIED"
-nswap="UNSPECIFIED"
-dumplo="UNSPECIFIED"
-dumproutine="UNSPECIFIED"
+if [ $# -ne 1 ]; then
+	echo "usage: $0 machinename"
+	exit 1
+fi
 
-LOWDM=0 NKL=1
-NACC=0 NBK=0 NCAT=0 NCSS=0 NDH=0 NDM=0 NDMC=0 NDN=0 NDR=0 NDVHP=0 NDZ=0
-NEC=0 NEN=0 NETH=0 NHK=0 NHP=0 NHS=0 NHT=0 NIL=0 NIMP=0 NLP=0 NPTY=0
-NPUP=0 NRF=0 NRK=0 NRL=0 NRM=0 NRP=0 NSRI=0 NTM=0 NTS=0 NUN=0 NVP=0 NVV=0
-NXP=0 NXP_CONTROLLER=0 NDMBB=0
+MACHINE=$1
+if [ ! -s $MACHINE ]; then
+	echo "$0: unable to read $MACHINE."
+	exit 1
+fi
 
-machine=$1
+# read in specification file
+eval `awk '/^#/ || /^$/ || /^	/ {next} $1 != "" { printf "%s=\\"%s\\"\\n", $1, $2 }' $MACHINE`
 
-: read in specification file
-eval `awk '/^#/ {next} $1 != "" { printf "%s=\\"%s\\"\\n", $1, $2 }' $machine`
+if [ ! "$MAXUSERS" ]; then
+	echo "$0: maxusers not set in $MACHINE."
+	exit 1
+fi
 
-case $pdp11 in
-	GENERIC|40|60)
-		splfix=:splfix.movb ;;
-	34|23|24)
-		splfix=:splfix.mtps ;;
-	44|45|70)
-		splfix=:splfix.spl ;;
+if [ ! "$TIMEZONE" ]; then
+	echo "$0: timezone not set in $MACHINE."
+	exit 1
+fi
+
+if [ ! "$DST" ]; then
+	echo "$0: dst flag not set in $MACHINE."
+	exit 1
+fi
+
+cat << EOF > $LO
+/*
+ * This file is generated by the configuration script sys/conf/config.
+ *
+ * It contains a list of kernel options, used when compiling the kernel
+ * as well as in a few of the application programs.
+ *
+ * All defines previously found in the whoami.h file have been moved
+ * into this file, as well as several originally found in device header
+ * files.  Do not hand edit unless you know what you're doing.  (You
+ * probably shouldn't hand edit anyway...)  See sys/conf/GENERIC for a
+ * list of available options and explanation as to what an option does,
+ * and sys/conf/README for more information.
+ */
+
+EOF
+
+case $PDP11 in
+	23|24|34)
+		SPLFIX=:splfix.mtps
+		echo "#define KERN_NONSEP"	>> $LO ;;
+	GENERIC)
+		SPLFIX=:splfix.movb ;;
+#		echo "#define KERN_NONSEP"	>> $LO
+#		if [ $NONFP = NO ]; then
+#			echo "NONFP changed; should be set for GENERIC kernels."
+#			NONFP=YES
+#		fi ;;
+	35|40|60)
+		SPLFIX=:splfix.movb
+		echo "#define KERN_NONSEP"	>> $LO ;;
+	53|73|83)
+		SPLFIX=:splfix.mtps ;;
+	44|45|50|55|70|84)
+		SPLFIX=:splfix.spl ;;
 	*)
-		echo "Unrecognized PDP11 type"
+		echo "$0: unrecognized PDP11 type $PDP11."
+		echo 'use GENERIC, 23, 24, 34, 35, 40, 44, 45, 50, 53, 55,'
+		echo '	60, 70, 73, 83, 84.'
 		exit 1 ;;
 esac
 
-if [ $NKL -lt 1 ]
-then
-	echo "NKL must be at least one (for the console)"
+if mkdir ../$MACHINE ; then
+	echo "Creating ../$MACHINE."
+	chmod 775 ../$MACHINE
+else
 	exit 1
 fi
 
-if [ -d ../$machine ]
-then
-	echo "../$machine: directory exists"
+if [ $NKL -lt 1 ]; then
+	echo "$0: NKL must be at least one (for the console)."
 	exit 1
 fi
-echo "Making ../$machine."
-mkdir ../$machine
 
-: copy in the standard configuration files, etc.
-: copy in the cpu-dependent files and modify as necessary
+# Copy in the standard configuration files, boot program,
+# makefiles, and cpu-dependent files.  Modify as necessary.
 
-echo "Copying in configuration files."
-
-cp c.c genassym.c ioconf.c l.s param.c whoami.h localopts.h param.h \
-	:comm-to-bss $splfix ../$machine
-cp includes/* ../$machine
-
-echo "Setting up boot.s, Makefile, whoami.h, param.c, ioconf.c."
-
-if [ $bootdev = "none" ]
-then
-	bootdev="no"
+if [ $MACHINE = VAX ]; then
+	echo "Copying standard VAX files to ../$MACHINE."
+	cp VAX.compile/VAX.c VAX.compile/Makefile ../$MACHINE
+else
+	echo "Copying standard files to ../$MACHINE."
+	cp $SPLFIX ../$MACHINE/SPLFIX
+	cp boot/${BOOTDEV}boot.s ../$MACHINE/boot.s
+	cp Makefile Make.sys Make.net Make.pdpuba Make.pdp \
+		Make.pdpmba ../$MACHINE
 fi
 
-: copy in boot program and makefiles, set the mode
+sed	-e "s/%ROOTDEV%/$ROOTDEV/" \
+	-e "s/%SWAPDEV%/$SWAPDEV/" \
+	-e "s/%PIPEDEV%/$PIPEDEV/" \
+	-e "s/%NSWAP%/$NSWAP/" \
+	-e "s/%SWAPLO%/$SWAPLO/" \
+	-e "s/%DUMPDEV%/$DUMPDEV/" \
+	-e "s/%DUMPLO%/$DUMPLO/" \
+	-e "s/%DUMPROUTINE%/$DUMPROUTINE/" < ioconf.c > ../$MACHINE/ioconf.c
 
-cp boot/${bootdev}boot.s ../$machine/boot.s
-cp makefiles/* ../$machine
+sed	-e "s/%TIMEZONE%/$TIMEZONE/" \
+	-e "s/%DST%/$DST/" \
+	-e "s/%MAXUSERS%/$MAXUSERS/" < param.c > ../$MACHINE/param.c
 
-chmod 664 ../$machine/*
+echo "Setting configuration options for $MACHINE."
 
-ed - ../$machine/Makefile << EOF
-/%SPLFIX%/s//$splfix/
-/%MAXUSERS%/s//$maxusers/
-w
-q
-EOF
+if [ $IDENT != GENERIC ]; then
+	echo "#define $IDENT"		>> $LO
+fi
+echo "#define PDP11	$PDP11"		>> $LO
+echo "#define MAXMEM	$MAXMEM"	>> $LO
+echo "#define LINEHZ	$LINEHZ"	>> $LO
+if [ $NONFP = YES ]; then
+	echo "#define NONFP 1"		>> $LO
+fi
+echo "#ifdef KERNEL"			>> $LO
+echo "#define NBUF	$NBUF"		>> $LO
 
-ed - ../$machine/whoami.h << EOF
-/%PDP%/s//$pdp11/
-g/%IDENT%/s//$ident/
-w
-q
-EOF
+if [ $UNIBUS_MAP = YES ]; then
+	echo "#define UNIBUS_MAP 1"	>> $LO
+fi
+if [ $Q22 = YES ]; then
+	echo "#define Q22 1"		>> $LO
+fi
+if [ $VIRUS_VFORK = YES ]; then
+	echo "#define VIRUS_VFORK 1"	>> $LO
+fi
+if [ $CGL_RTP = YES ]; then
+	echo "#define CGL_RTP 1"	>> $LO
+fi
+if [ $UCB_METER = YES ]; then
+	echo "#define UCB_METER 1"	>> $LO
+fi
+if [ $UCB_RUSAGE = YES ]; then
+	echo "#define UCB_RUSAGE 1"	>> $LO
+fi
+if [ $NOKA5 = YES ]; then
+	echo "#define NOKA5 1"		>> $LO
+fi
+if [ $UCB_NET = YES ]; then
+	echo "#define UCB_NET 1"	>> $LO
+	echo "#define INET 1"		>> $LO
+	echo "#define TCP_COMPAT_42"	>> $LO
+	if [ $NOKA5 = YES ] ; then
+		echo "You may not define both NOKA5 and UCB_NET."
+		exit 1
+	fi
+fi
+if [ $BADSECT = YES ]; then
+	echo "#define BADSECT 1"	>> $LO
+fi
+if [ $DIAGNOSTIC = YES ]; then
+	echo "#define DIAGNOSTIC 1"	>> $LO
+	echo "#define ICMPPRINTFS"	>> $LO
+fi
+if [ $UCB_FRCSWAP = YES ]; then
+	echo "#define UCB_FRCSWAP 1"	>> $LO
+fi
+if [ $UCB_CLIST = YES ]; then
+	echo "#define UCB_CLIST 1"	>> $LO
+fi
+if [ $SMALL = YES ]; then
+	echo "#define SMALL 1"		>> $LO
+fi
+if [ $PROFILE = YES ]; then
+	echo "#define PROFILE 1"	>> $LO
+fi
+echo "#endif /* KERNEL */"		>> $LO
 
-ed - ../$machine/param.c << EOF
-/%TIMEZONE%/s//$timezone/
-/%DST%/s//$dst/
-w
-q
-EOF
+echo "Creating device header files."
 
-ed - ../$machine/ioconf.c << EOF
-/%ROOTDEV%/s//$rootdev/
-/%SWAPDEV%/s//$swapdev/
-/%PIPEDEV%/s//$pipedev/
-/%DUMPDEV%/s//$dumpdev/
-/%NSWAP%/s//$nswap/
-/%SWPLO%/s//$swplo/
-/%DUMPLO%/s//$dumplo/
-g/%DUMPROUTINE%/s//$dumproutine/
-w
-q
-EOF
+echo "#define NCSS	$NCSS"		> ../$MACHINE/css.h
+echo "#define NDE	$NDE"		> ../$MACHINE/de.h
+echo "#define NDH	$NDH"		> ../$MACHINE/dh.h
+echo "#define NDM	$NDM"		>> ../$MACHINE/dh.h
+echo "#define NDHU	$NDHU"		> ../$MACHINE/dhu.h
+echo "#define NDMC	$NDMC"		> ../$MACHINE/dmc.h
+echo "#define NDR	$NDR"		> ../$MACHINE/dr.h
+echo "#define NDZ	$NDZ"		> ../$MACHINE/dz.h
+echo "#define NEC	$NEC"		> ../$MACHINE/ec.h
+echo "#define NEN	$NEN"		> ../$MACHINE/en.h
+echo "#define NETHER	$NETHER"	> ../$MACHINE/ether.h
+echo "#define NHT	$NHT"		> ../$MACHINE/ht.h
+echo "#define NHY	$NHY"		> ../$MACHINE/hy.h
+echo "#define NIL	$NIL"		> ../$MACHINE/il.h
+echo "#define NIMP	$NIMP"		> ../$MACHINE/imp.h
+echo "#define NKL	$NKL"		> ../$MACHINE/cn.h
+echo "#define NLOOP	$NLOOP"		> ../$MACHINE/loop.h
+echo "#define NLP	$NLP"		> ../$MACHINE/lp.h
+echo "#define LP_MAXCOL	$LP_MAXCOL"	>> ../$MACHINE/lp.h
+echo "#define NPTY	$NPTY"		> ../$MACHINE/pty.h
+echo "#define NPUP	$NPUP"		> ../$MACHINE/npup.h
+echo "#define NQE	$NQE"		> ../$MACHINE/qe.h
+echo "#define NRAM	$NRAM"		> ../$MACHINE/ram.h
+echo "#define NRK	$NRK"		> ../$MACHINE/rk.h
+echo "#define NRX	$NRX"		> ../$MACHINE/rx.h
+echo "#define NSL	$NSL"		> ../$MACHINE/sl.h
+echo "#define NSRI	$NSRI"		> ../$MACHINE/sri.h
+echo "#define NTB	$NTB"		> ../$MACHINE/tb.h
+echo "#define NTS	$NTS"		> ../$MACHINE/ts.h
+echo "#define NVV	$NVV"		> ../$MACHINE/vv.h
 
-:  Now edit all of the device header files.
+echo "#define NACC	$NACC"		> ../$MACHINE/acc.h
+if [ $PLI = YES ]; then
+	echo "#define PLI 1"		>> ../$MACHINE/acc.h
+fi
 
-echo "Setting up device header files."
+echo "#define NHK	$NHK"		> ../$MACHINE/hk.h
+if [ $DUMPROUTINE = hkdump ]; then
+	echo "#define HK_DUMP 1"	>> ../$MACHINE/hk.h
+fi
 
-ed - ../$machine/acc.h << EOF
-/%NACC%/s//$NACC/
-w
-q
-EOF
+echo "#define NRAC	$NRAC"		> ../$MACHINE/ra.h
+echo "#define NRAD	$NRAD"		>> ../$MACHINE/ra.h
+if [ $DUMPROUTINE = radump ]; then
+	echo "#define RA_DUMP 1"	>> ../$MACHINE/ra.h
+fi
 
-ed - ../$machine/bk.h << EOF
-/%NBK%/s//$NBK/
-w
-q
-EOF
+echo "#define NRL	$NRL"		> ../$MACHINE/rl.h
+if [ $DUMPROUTINE = rldump ]; then
+	echo "#define RL_DUMP 1"	>> ../$MACHINE/rl.h
+fi
 
-ed - ../$machine/cat.h << EOF
-/%NCAT%/s//$NCAT/
-w
-q
-EOF
+echo "#define NSI	$NSI"		> ../$MACHINE/si.h
+if [ $DUMPROUTINE = sidump ]; then
+	echo "#define SI_DUMP 1"	>> ../$MACHINE/si.h
+fi
 
-ed - ../$machine/css.h << EOF
-/%NCSS%/s//$NCSS/
-w
-q
-EOF
+echo "#define NTM	$NTM"		> ../$MACHINE/tm.h
+if [ $AVIVTM = YES ] ; then
+	echo "#define AVIVTM 1"		>> ../$MACHINE/tm.h
+fi
 
-ed - ../$machine/dmbb.h << EOF
-/%NDMBB%/s//$NDMBB/
-w
-q
-EOF
+echo "#define NXPD	$NXPD"		> ../$MACHINE/xp.h
+echo "#define NXPC	$NXPC"		>> ../$MACHINE/xp.h
+if [ $DUMPROUTINE = xpdump ]; then
+	echo "#define XP_DUMP 1"	>> ../$MACHINE/xp.h
+fi
+if [ $XP_PROBE = YES ]; then
+	echo "#define XP_PROBE 1"	>> ../$MACHINE/xp.h
+fi
 
-ed - ../$machine/dh.h << EOF
-/%NDH%/s//$NDH/
-/%NDM%/s//$NDM/
-/%LOWDM%/s//$LOWDM/
-w
-q
-EOF
+# save copy of localopts.h
+cp $LO ../$MACHINE
 
-ed - ../$machine/dmc.h << EOF
-/%NDMC%/s//$NDMC/
-w
-q
-EOF
-
-ed - ../$machine/dn.h << EOF
-/%NDN%/s//$NDN/
-w
-q
-EOF
-
-ed - ../$machine/dr.h << EOF
-/%NDR%/s//$NDR/
-w
-q
-EOF
-
-ed - ../$machine/dvhp.h << EOF
-/%NDVHP%/s//$NDVHP/
-w
-q
-EOF
-
-ed - ../$machine/ec.h << EOF
-/%NEC%/s//$NEC/
-w
-q
-EOF
-
-ed - ../$machine/en.h << EOF
-/%NEN%/s//$NEN/
-w
-q
-EOF
-
-ed - ../$machine/eth.h << EOF
-/%NETH%/s//$NETH/
-w
-q
-EOF
-
-ed - ../$machine/dz.h << EOF
-/%NDZ%/s//$NDZ/
-w
-q
-EOF
-
-ed - ../$machine/hk.h << EOF
-/%NHK%/s//$NHK/
-w
-q
-EOF
-
-ed - ../$machine/hp.h << EOF
-/%NHP%/s//$NHP/
-w
-q
-EOF
-
-ed - ../$machine/hs.h << EOF
-/%NHS%/s//$NHS/
-w
-q
-EOF
-
-ed - ../$machine/ht.h << EOF
-/%NHT%/s//$NHT/
-w
-q
-EOF
-
-ed - ../$machine/il.h << EOF
-/%NIL%/s//$NIL/
-w
-q
-EOF
-
-ed - ../$machine/imp.h << EOF
-/%NIMP%/s//$NIMP/
-w
-q
-EOF
-
-ed - ../$machine/kl.h << EOF
-/%NKL%/s//$NKL/
-w
-q
-EOF
-
-ed - ../$machine/lp.h << EOF
-/%NLP%/s//$NLP/
-w
-q
-EOF
-
-ed - ../$machine/pty.h << EOF
-/%NPTY%/s//$NPTY/
-w
-q
-EOF
-
-ed - ../$machine/pup.h << EOF
-/%NPUP%/s//$NPUP/
-w
-q
-EOF
-
-ed - ../$machine/rf.h << EOF
-/%NRF%/s//$NRF/
-w
-q
-EOF
-
-ed - ../$machine/rk.h << EOF
-/%NRK%/s//$NRK/
-w
-q
-EOF
-
-ed - ../$machine/rl.h << EOF
-/%NRL%/s//$NRL/
-w
-q
-EOF
-
-ed - ../$machine/rm.h << EOF
-/%NRM%/s//$NRM/
-w
-q
-EOF
-
-ed - ../$machine/rp.h << EOF
-/%NRP%/s//$NRP/
-w
-q
-EOF
-
-ed - ../$machine/sri.h << EOF
-/%NSRI%/s//$NSRI/
-w
-q
-EOF
-
-ed - ../$machine/tm.h << EOF
-/%NTM%/s//$NTM/
-w
-q
-EOF
-
-ed - ../$machine/ts.h << EOF
-/%NTS%/s//$NTS/
-w
-q
-EOF
-
-ed - ../$machine/un.h << EOF
-/%NUN%/s//$NUN/
-w
-q
-EOF
-
-ed - ../$machine/vp.h << EOF
-/%NVP%/s//$NVP/
-w
-q
-EOF
-
-ed - ../$machine/vv.h << EOF
-/%NVV%/s//$NVV/
-w
-q
-EOF
-
-ed - ../$machine/xp.h << EOF
-/%NXP%/s//$NXP/
-/%NXP_CONTROLLER%/s//$NXP_CONTROLLER/
-w
-q
-EOF
-
-echo ""
-echo "Now edit the header files in ../$machine to change any local options"
-echo "or parameters in localopts.h, param.c and the device headers."
-echo "Remember to edit \"Makefile\" if you need to add optional device"
-echo "drivers, then \"make depend\".  You will also have to add any optional"
-echo "files to the load rules in Makefile.  If you are going to run an"
-echo "overlaid kernel you will probably also have to edit the overlay"
-echo "definitions in the Makefile."
+# set permissions
+chmod 664 ../$MACHINE/*
