2.9BSD (1983, files dated up to March 1984)
/ comes from the root filesystem dump (tape file 7), and /usr from
usr.tar. The root dump was cross-checked against the separately
archived root.tar: only etc/utmp differs.

Source: https://www.tuhs.org/Archive/Distributions/UCB/2BSD/2.9BSD/

    This directory contains the following files:

    -r--r--r--  1 sms  staff     12696 Sep  7  1993 file1.gz
    -r--r--r--  1 sms  staff     12744 Jan 24 19:40 file1.ts.gz
    -r--r--r--  1 sms  staff      5630 Sep  7  1993 file2.gz
    -r--r--r--  1 sms  staff       270 Sep  7  1993 file3.gz
    -r--r--r--  1 sms  staff     13188 Sep  7  1993 file4.gz
    -r--r--r--  1 sms  staff     12976 Sep  7  1993 file5.gz
    -r--r--r--  1 sms  staff     12342 Sep  7  1993 file6.gz
    -r--r--r--  1 sms  staff    875950 Apr 20 22:37 file7.gz
    -r--r--r--  1 sms  wheel  10801907 Apr 20 21:45 usr.tar.gz

    	file1 is the bootblock+bootprogram for the TU10/TU16 tape
    	file1.ts is the bootblock+bootprogram for the TS11 tape
    	file2 is the standalone 'cat' program
    	file3 is the Table Of Contents (used by the 'cat' program)
    	file4 is the standalone 'mkfs' program
    	file5 is the standalone 'restor' program
    	file6 is the standalone 'icheck' program
    	file7 is the dump of the root filesystem
    	usr.tar is a tar image of /usr with relative pathnames (i.e.  no
    		leading /usr.  you load this by cd /usr; tar -xpf ...)

    	To create a tape you will need to place these files in order
    	using the following blocking factors:

    		dd if=file1 of=/dev/nrmt0 bs=512
    		dd if=file2 of=/dev/nrmt0 bs=1024
    		dd if=file3 of=/dev/nrmt0 bs=1024
    		dd if=file4 of=/dev/nrmt0 bs=1024
    		dd if=file5 of=/dev/nrmt0 bs=1024
    		dd if=file6 of=/dev/nrmt0 bs=1024
    		dd if=file7 of=/dev/nrmt0 bs=10240
    		dd if=usr.tar of=/dev/nrmt0 bs=10240

    	Good Luck.
    		Steven

Import notes: kept 7161 files; dropped 406 a.out executables (PDP-11/VAX); dropped 53 other binary files (data, boot blocks, generated string tables); dropped 36 compiled object libraries.

Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01Vb1qstb69mh3NKDCWZ2NBD

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,11 +1,53 @@
-PATH=/bin:/usr/bin
+:  rc for use with autoreboot
+:  '/etc/rc [ autoboot | fastboot  [ powerfail | "" ] ]'
+HOME=/; export HOME
+PATH=/etc:/bin:/usr/bin; export PATH
+case $2 in 
+powerfail)
+	echo REBOOTING AFTER POWER FAILURE >/dev/console
+	;;
+esac
+case $1 in
+autoboot)
+	echo Automatic reboot in progress... >/dev/console
+	date >/dev/console
+	fsck -p -t fsck.tmp >/dev/console 2>&1
+	case $? in
+	0)
+		;;
+	4)
+		echo "Root was modified-- rebooting." >/dev/console
+		reboot -n
+		;;
+	8)
+		echo "Automatic filesystem check failed... help!" >/dev/console
+		exit 1
+		;;
+	12)
+		echo "Reboot interrupted" >/dev/console
+		exit 1
+		;;
+	*)
+		echo "Unknown error in reboot" > /dev/console
+		exit 1
+		;;
+	esac
+;;
+esac
+date >/dev/console
 cp /dev/null /etc/mtab
-date > /dev/console
 cp /dev/null /etc/utmp
+mount -a			>/dev/console 2>&1
+savecore /usr/sys >/dev/console 2>&1
+/usr/lib/ex3.7preserve -a
 rm -rf /usr/tmp/*
-find /usr/preserve -mtime +4 -a \! -type d -a -exec rm -r {} \;
-(cd /tmp; /usr/ucb/lib/ex3.6preserve -a)
-rm -f /tmp/*
-rm -fr /usr/lib/learn/play/*
+rm -rf /tmp/*
+rm -f /usr/spool/uucp/LCK..*
+rm -f /usr/spool/lpd/lock
+rm -f /usr/spool/vpd/lock
 /etc/update
 /etc/cron
+ps -U
+/etc/accton /usr/adm/acct
+/etc/hostname hostnameunknown
+exit 0
